// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Context;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(BaseDbContext))]
    partial class BaseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.1.22076.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Brand", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Audi"
                        },
                        new
                        {
                            Id = 2,
                            Name = "BMW"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mercedes"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Volkswagen"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Volvo"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ford"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CarState")
                        .HasColumnType("int")
                        .HasColumnName("State");

                    b.Property<int>("ColorId")
                        .HasColumnType("int")
                        .HasColumnName("ColorId");

                    b.Property<int>("ModelId")
                        .HasColumnType("int")
                        .HasColumnName("ModelId");

                    b.Property<short>("ModelYear")
                        .HasColumnType("smallint")
                        .HasColumnName("ModelYear");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Plate");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("ModelId");

                    b.ToTable("Car", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarState = 0,
                            ColorId = 1,
                            ModelId = 1,
                            ModelYear = (short)2001,
                            Plate = "60TR60"
                        },
                        new
                        {
                            Id = 2,
                            CarState = 1,
                            ColorId = 2,
                            ModelId = 2,
                            ModelYear = (short)2002,
                            Plate = "34TR60"
                        },
                        new
                        {
                            Id = 3,
                            CarState = 2,
                            ColorId = 3,
                            ModelId = 3,
                            ModelYear = (short)2003,
                            Plate = "45TR60"
                        },
                        new
                        {
                            Id = 4,
                            CarState = 0,
                            ColorId = 4,
                            ModelId = 4,
                            ModelYear = (short)2004,
                            Plate = "35TR60"
                        },
                        new
                        {
                            Id = 5,
                            CarState = 1,
                            ColorId = 5,
                            ModelId = 5,
                            ModelYear = (short)2005,
                            Plate = "55TR60"
                        },
                        new
                        {
                            Id = 6,
                            CarState = 2,
                            ColorId = 6,
                            ModelId = 6,
                            ModelYear = (short)2006,
                            Plate = "66TR60"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Color", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Black"
                        },
                        new
                        {
                            Id = 2,
                            Name = "White"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Red"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Blue"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Silver"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Yellow"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Green"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Orange"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Pink"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Purple"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Brown"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Grey"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Maroon"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Navy"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Lime"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Aqua"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Teal"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Olive"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Maroon"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Aquamarine"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Coral"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Crimson"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Cyan"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Fuchsia"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Gold"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Khaki"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Lavender"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Lime"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Magenta"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Navy"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Olive"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Plum"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Salmon"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Silver"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Tan"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Teal"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Violet"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Yellow"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Beige"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Brown"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Cream"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Gold"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Grey"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Ivory"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Mauve"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Ochre"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Puce"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Rust"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Tan"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Teal"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Fuel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Fuel", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Petrol"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Diesel"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Gas"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Electric"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Hybrid"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BrandId")
                        .HasColumnType("int")
                        .HasColumnName("BrandId");

                    b.Property<double>("DailyPrice")
                        .HasColumnType("float");

                    b.Property<int>("FuelId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.Property<int>("TransmissionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("FuelId");

                    b.HasIndex("TransmissionId");

                    b.ToTable("Model", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            DailyPrice = 1000.0,
                            FuelId = 1,
                            ImageUrl = "",
                            Name = "A1",
                            TransmissionId = 1
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 2,
                            DailyPrice = 600.0,
                            FuelId = 2,
                            ImageUrl = "",
                            Name = "A3",
                            TransmissionId = 2
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 3,
                            DailyPrice = 1000.0,
                            FuelId = 3,
                            ImageUrl = "",
                            Name = "A4",
                            TransmissionId = 1
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 4,
                            DailyPrice = 750.0,
                            FuelId = 4,
                            ImageUrl = "",
                            Name = "A5",
                            TransmissionId = 2
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 5,
                            DailyPrice = 500.0,
                            FuelId = 5,
                            ImageUrl = "",
                            Name = "A6",
                            TransmissionId = 1
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 6,
                            DailyPrice = 2000.0,
                            FuelId = 6,
                            ImageUrl = "",
                            Name = "A7",
                            TransmissionId = 2
                        });
                });

            modelBuilder.Entity("Domain.Entities.Transmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Transmission", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Manual"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Automatic"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Car", b =>
                {
                    b.HasOne("Domain.Entities.Color", "Color")
                        .WithMany("Cars")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Model", "Model")
                        .WithMany("Cars")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Domain.Entities.Model", b =>
                {
                    b.HasOne("Domain.Entities.Brand", "Brand")
                        .WithMany("Models")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Fuel", "Fuel")
                        .WithMany("Models")
                        .HasForeignKey("FuelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Transmission", "Transmission")
                        .WithMany("Models")
                        .HasForeignKey("TransmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Fuel");

                    b.Navigation("Transmission");
                });

            modelBuilder.Entity("Domain.Entities.Brand", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("Domain.Entities.Color", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("Domain.Entities.Fuel", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("Domain.Entities.Model", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("Domain.Entities.Transmission", b =>
                {
                    b.Navigation("Models");
                });
#pragma warning restore 612, 618
        }
    }
}
